import { FormControl } from "@angular/forms";
import { AppSelectOptionData } from "../core-ui/components/app-select.component";
import { AppFormGroup } from "../utils/forms";

export interface ShowCol {
  headerName: string;
  field: string;
  isDisplay: boolean;
  canAccess: boolean;
  isDecimal?: boolean;
  isPin: boolean;
  pinned?: string;
  width?: number;
  editable?: boolean;
  valueSetter?: any;
}

export class PmeAgGridDisplayList {
  static get items(): ShowCol[] {
    return [
      {
        headerName: 'ITEM ID',
        field: 'item_id',
        isDisplay: true,
        isPin: true,
        canAccess: true,
      },
      {
        headerName: 'PRODUCT TYPE',
        field: 'product_type',
        isDisplay: true,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'RECORD TYPE',
        field: 'record_type',
        isDisplay: true,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'PRIORITY',
        field: 'priority_of_review',
        isDisplay: true,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'STATUS',
        field: 'gi_status',
        isDisplay: true,
        isPin: false,
        canAccess: true,
      },

      {
        headerName: 'CUSTOMER',
        field: 'customer_name',
        isDisplay: true,
        canAccess: true,
        isPin: false,
      },
      {
        headerName: 'PRODUCT NAME',
        field: 'gi_product_name',
        isDisplay: true,
        canAccess: true,
        isPin: false,
      },
      {
        headerName: 'MATERIAL CODE',
        field: 'gi_material_code',
        isDisplay: true,
        isPin: false,
        canAccess: true,
        width: 100,
      },
      {
        headerName: 'MATERIAL NAME',
        field: 'gi_material_name',
        isDisplay: true,
        canAccess: true,
        isPin: false,
      },
      {
        headerName: 'REGION',
        field: 'gi_region',
        isDisplay: true,
        isPin: false,
        canAccess: true,
        width: 100,
      },
      {
        headerName: 'SALES DISTRICT',
        field: 'gi_sales_district',
        isDisplay: true,
        isPin: false,
        canAccess: true,
        width: 100,
      },
      {
        headerName: 'UOM',
        field: 'uom',
        isDisplay: true,
        isPin: false,
        canAccess: true,
        width: 100,
      },
      {
        headerName: 'INVOICE CURRENCY',
        field: 'invoice_currency',
        isDisplay: false,
        canAccess: true,
        isPin: false,
      },
      {
        headerName: 'LAST INVOICE PRICE',
        field: 'last_invoice_price',
        isDecimal: true,
        isDisplay: false,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'DVP MODEL PRICE',
        field: 'dvp_model_price',
        isDecimal: true,
        isDisplay: false,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'LAST VALIDATED PRICE',
        field: 'last_validated_price',
        isDecimal: true,
        isDisplay: false,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'REQUESTED SELLING PRICE(RSP) IN LOCAL CURRENCY',
        field: 'requested_selling_price',
        isDecimal: true,
        isDisplay: false,
        isPin: false,
        canAccess: true,
        editable: true,
        valueSetter: true,
      },
      {
        headerName: 'ANNUALIZED VOLUME COMMITMENT',
        field: 'annualized_volume_commitment',
        isDecimal: true,
        isDisplay: false,
        isPin: false,
        canAccess: true,
        editable: true,
        valueSetter: true,
      },
      {
        headerName: 'LAST TWELVE MONTH VOLUME',
        field: 'last_twelve_months_volume',
        isDisplay: false,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'PRICE VALID FROM',
        field: 'price_valid_from',
        isDisplay: false,
        isPin: false,
        canAccess: true,
        editable: true,
      },
      {
        headerName: 'PRICE VALID TO',
        field: 'price_valid_to',
        isDisplay: false,
        isPin: false,
        canAccess: true,
        editable: true,
      },
      {
        headerName: 'CURRENT SAP PRICE VALIDITY DATE',
        field: 'current_sap_price_validity_date',
        isDisplay: false,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'CUSTOMER CODE',
        field: 'gi_customer_code',
        isDisplay: false,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'PORTFOLIO STRATEGY',
        field: 'gi_portfolio_strategy',
        isDisplay: false,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'EXWORKS DVP PRICE',
        field: 'gi_exworks_dvp_price',
        isDecimal: true,
        isDisplay: false,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'DVP MODEL PRICE INVOICE CURRENCY ',
        field: 'gi_dvp_model_price_in_invoice_currency',
        isDecimal: true,
        isDisplay: false,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'VBP PRICE',
        field: 'gi_vbp_price',
        isDecimal: true,
        isDisplay: false,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'LAST INVOICE PRICE DATE',
        field: 'gi_last_invoice_price_date',
        isDisplay: false,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'LAST INVOICE PRICE CURRENCY',
        field: 'gi_last_invoice_price_currency',
        isDisplay: false,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'LAST INVOICE PRICE IN LOCAL CURRENCY',
        field: 'gi_last_invoice_price_in_local_currency',
        isDecimal: true,
        isDisplay: false,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'LAST VALIDATED PRICE CURRENCY',
        field: 'gi_last_validated_price_currency',
        isDisplay: false,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'BUSINESS TYPE',
        field: 'pdm_business_type',
        isDisplay: false,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'NBA COMPANY NAME',
        field: 'pdm_nba_company_name',
        isDisplay: false,
        isPin: false,
        canAccess: true,
        editable: true,
      },
      {
        headerName: 'NBA PRODUCT',
        field: 'pdm_nba_product',
        isDisplay: false,
        isPin: false,
        canAccess: true,
        editable: true,
      },
      {
        headerName: 'RELATIVE STRENGTH HUNTSMAN',
        field: 'pdm_rltv_strength_huntsman',
        isDecimal: true,
        isDisplay: false,
        isPin: false,
        canAccess: true,
        editable: true,
        valueSetter: true,
      },
      {
        headerName: 'RELATIVE STRENGTH NBA',
        field: 'pdm_rltv_strength_nba',
        isDisplay: false,
        isPin: false,
        canAccess: true,
        editable: true,
      },
      {
        headerName: 'NBA PRICE CURRENCY',
        field: 'pdm_nba_price_currency',
        isDisplay: false,
        isPin: false,
        canAccess: true,
        editable: true,
      },
      {
        headerName: 'NBA PRICE PER KG',
        field: 'pdm_nba_price_per_kg',
        isDecimal: true,
        isDisplay: false,
        isPin: false,
        canAccess: true,
        editable: true,
        valueSetter: true,
      },
      {
        headerName: 'SOURCE OF NBA PRICE',
        field: 'pdm_source_of_nba_price',
        isDisplay: false,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'THIRD PARTY',
        field: 'pdm_third_party',
        isDisplay: false,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'ADJUSTED NBA PRICE PER KG',
        field: 'pdm_adjusted_nba_price_per_kg',
        isDecimal: true,
        isDisplay: false,
        isPin: false,
        canAccess: true,
        editable: true,
        valueSetter: true,
      },
      {
        headerName: 'PRODUCT DIFFERENTIATION',
        field: 'pdm_product_differentiation',
        isDisplay: false,
        isPin: false,
        canAccess: true,
        editable: true,
      },
      {
        headerName: 'TOP VALUE DRIVERS DIFFERENTIATION',
        field: 'pdm_top_value_drivers_differentiation',
        isDisplay: false,
        isPin: false,
        canAccess: true,
        editable: true,
      },
      {
        headerName: 'OTHER VALUE DRIVERS DIFFERENTIATION',
        field: 'pdm_other_value_drivers_differentiation',
        isDisplay: false,
        isPin: false,
        canAccess: true,
        editable: true,
      },
      {
        headerName: 'SPOT DEAL',
        field: 'pdm_spot_deal',
        isDisplay: false,
        isPin: false,
        canAccess: true,
        editable: true,
      },
      {
        headerName: 'PRODUCT SITE',
        field: 'ai_product_site',
        isDisplay: false,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'SALES ORGANIZATION',
        field: 'ai_sales_organization',
        isDisplay: false,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'FREIGHT',
        field: 'ai_freight',
        isDecimal: true,
        isDisplay: false,
        isPin: false,
        canAccess: true,
        valueSetter: true,
      },
      {
        headerName: 'DUTY APPLIED',
        field: 'ai_duty_applied',
        isDisplay: false,
        isPin: false,
        canAccess: true,
        valueSetter: true,
      },
      {
        headerName: 'LAST MILE',
        field: 'ai_last_mile',
        isDisplay: false,
        isPin: false,
        canAccess: true,
        valueSetter: true,
      },
      {
        headerName: 'BUFFER',
        field: 'ai_buffer',
        isDisplay: false,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'COMMISSION',
        field: 'ai_commission',
        isDisplay: false,
        isPin: false,
        canAccess: true,
        valueSetter: true,
      },
      {
        headerName: 'REBATE',
        field: 'ai_rebate',
        isDisplay: false,
        isPin: false,
        canAccess: true,
        valueSetter: true,
      },
      {
        headerName: 'FIX RATE',
        field: 'ai_fx_rate',
        isDecimal: true,
        isDisplay: false,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'PARTY',
        field: 'ai_party',
        isDisplay: false,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'FREIGHT SURCHARGE',
        field: 'ai_freight_surcharge',
        isDecimal: true,
        isDisplay: false,
        isPin: false,
        canAccess: true,
        editable: true,
        valueSetter: true,
      },
      {
        headerName: 'PROFIT SHARING',
        field: 'ai_profit_sharing',
        isDisplay: false,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'SALES REP JUSTIFICATION FOR LOWER RSP',
        field: 'srep_justification_for_lower_rsp',
        isDisplay: false,
        isPin: false,
        canAccess: true,
        editable: true,
      },
      {
        headerName: 'SALES REP JUSTIFICATION FOR LOWER VOLUME',
        field: 'srep_justification_for_lower_volume',
        isDisplay: false,
        isPin: false,
        canAccess: true,
        editable: true,
      },
      {
        headerName: 'SALES REP',
        field: 'gi_sales_rep_name',
        isDisplay: true,
        isPin: false,
        canAccess: true,
        width: 150,
      },
      {
        headerName: 'SALES MANAGER',
        field: 'gi_sales_manager_name',
        isDisplay: true,
        isPin: false,
        canAccess: true,
        width: 150,
      },
      {
        headerName: 'GMM',
        field: 'gi_gmm_name',
        isDisplay: true,
        canAccess: true,
        isPin: false,
      },
      {
        headerName: 'COMM DIR',
        field: 'gi_commercial_director_name',
        isDisplay: true,
        isPin: false,
        canAccess: true,
        width: 150,
      },
      {
        headerName: 'TOTAL PRODUCT COST',
        field: 'ai_total_product_cost',
        isDecimal: true,
        isDisplay: false,
        isPin: false,
        canAccess: true,
      },
      // {
      //   headerName: 'SM THRESHOLD NM',
      //   field: 'ti_sm_threshold_nm',
      //   isDecimal: true,
      //   isDisplay: false,
      //   isPin: false,
      //   canAccess: true,
      // },
      {
        headerName: 'SM THRESHOLD PRICE',
        field: 'sm_threshold_price',
        isDecimal: true,
        isDisplay: false,
        isPin: false,
        canAccess: true,
      },
      // {
      //   headerName: 'CD THRESHOLD NM',
      //   field: 'ti_cd_threshold_nm',
      //   isDecimal: true,
      //   isDisplay: false,
      //   isPin: false,
      //   canAccess: true,
      // },
      {
        headerName: 'REQUESTED SELLING PRICE NM',
        field: 'requested_selling_price_nm',
        isDecimal: true,
        isDisplay: false,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'LAST TRANSCTION NM',
        field: 'last_transaction_nm',
        isDecimal: true,
        isDisplay: false,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'LAST VALIDATED PRICE NM',
        field: 'last_validated_price_nm',
        isDecimal: true,
        isDisplay: false,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'RSP CHANGE % vs LAST TRANSACTED PRICE',
        field: 'rsp_change_vs_last_transacted_price',
        isDecimal: true,
        isDisplay: false,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'RSP CHANGE % vs LAST VALIDATED PRICE',
        field: 'rsp_change_vs_last_validated_price',
        isDecimal: true,
        isDisplay: false,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'RSP vs ADJUSTED NBA PRICE',
        field: 'rsp_vs_adjusted_nba_price',
        isDecimal: true,
        isDisplay: false,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'CD THRESHOLD PRICE',
        field: 'cd_threshold_price',
        isDecimal: true,
        isDisplay: false,
        isPin: false,
        canAccess: true,
      },
      // {
      //   headerName: 'IS DELETED',
      //   field: 'is_deleted',
      //   isDisplay: false,
      //   isPin: false,
      //   canAccess: true,
      // },
      // {
      //   headerName: 'DELETE REASON',
      //   field: 'delete_reason',
      //   isDisplay: false,
      //   isPin: false,
      //   canAccess: true,
      // },
    ];
  }
}
export class QuotationAgGridDisplayList {
  static get items(): ShowCol[] {
    return [
      {
        headerName: 'QUOTE ID',
        field: 'quote_id',
        isDisplay: true,
        isPin: true,
        canAccess: true,
      },
      {
        headerName: 'REQUEST DATE',
        field: 'created_date',
        isDisplay: true,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'REQUESTOR',
        field: 'user_name',
        isDisplay: true,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'STATUS',
        field: 'status',
        isDisplay: true,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'CUSTOMER CODE',
        field: 'customer_code',
        isDisplay: true,
        canAccess: true,
        isPin: false,
      },
      {
        headerName: 'CUSTOMER',
        field: 'customer_desc',
        isDisplay: true,
        canAccess: true,
        isPin: false,
      },
      {
        headerName: 'MATERIAL CODE',
        field: 'material_code',
        isDisplay: true,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'MATERIAL NAME',
        field: 'material_desc',
        isDisplay: true,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'SALES DISTRICT',
        field: 'sales_district',
        isDisplay: true,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'SALES ORGANIZATION',
        field: 'sales_organization',
        isDisplay: true,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'UOM',
        field: 'uom',
        isDisplay: true,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'CURRENCY',
        field: 'currency',
        isDisplay: true,
        canAccess: true,
        isPin: false,
      },
      {
        headerName: 'PRICE VALIDITY START SATE',
        field: 'price_validity_start_date',
        isDisplay: true,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'COMMITTED VOLUME',
        field: 'commited_volume',
        isDecimal: true,
        isDisplay: true,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'FILE',
        field: 'file_name',
        isDisplay: true,
        isPin: false,
        canAccess: true,
      },
      {
        headerName: 'Download',
        field: 'download',
        isDisplay: true,
        isPin: false,
        canAccess: true,
      },
    ];
  }
}

export class DvpModelValue {
  static get data(): any[] {
    return [
      'Enhanced Productivity',
      'Enhanced runability',
      'Durability',
      'High concentration',
      'Lower effluent output',
      'Lower electricity consumption',
      'Lower water consumption',
      'Lower steam consumption',
      'Lower total utility consumption',
      'Reduced inventory cost',
      'Reduced processign time',
      'Reduction in reprocessing',
      'Reduced recipe cost',
      'Avoid a specific product',
      'Increase first quality products',
      'Additional Process',
      'Reduced Chemical Waste',
      'Fastness',
      'Saving on discounts',
      'Lab testing',
      'New orders from brands',
      'Sustainability',
      'Oem support',
      'Technical service',
      'B&R support',
    ];
  }
}

